---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;

    events {
      worker_connections  10240;
    }

    http {
      server {
        listen       80;
        server_name  localhost;
        location / {
          root   /www; #Change this line
          index  index.html index.htm;
        }

        location /coa/ {
            alias /data/;
            autoindex on;
            autoindex_format html;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-web-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <title>Example</title>
        </head>
        <body>
            <a href="/coa/">[CoA]</a>
        </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-script-cm
data:
  run.bash: |
    #!/bin/sh

    # May change to rclone sync instead

    while :
    do
      # Use webmaster@napbiotec.io token to login 
      rclone copy GoogleDriveNAp: /data/napbiotec -vvv
      sleep 5m
    done
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-genuine-doc
  labels:
    app.kubernetes.io/name: genuine-doc
    app.kubernetes.io/instance: demo
spec:
  ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: genuine-doc
    app.kubernetes.io/instance: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-genuine-doc
  labels:
    app.kubernetes.io/name: genuine-doc
    app.kubernetes.io/instance: demo
spec:
  strategy: 
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: genuine-doc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: genuine-doc
        app.kubernetes.io/instance: demo
    spec:
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      containers:
        - name: genuine-doc
          image: "nginx:1.23.3"
          imagePullPolicy: IfNotPresent
          env: 
            - name: DUMMY_ENV
              value: "002"
          volumeMounts: 
            - mountPath: /data
              name: data
            - mountPath: /etc/nginx
              name: nginx-cfg
            - mountPath: /www
              name: nginx-web
          ports: 
            - containerPort: 80
          resources: 
            {}
        - command:
          - /bin/sh
          - -c
          - /scripts/run.bash
          image: rclone/rclone:1.62.2
          name: rclone
          volumeMounts:
          - mountPath: /config/rclone
            name: config
          - mountPath: /scripts
            name: scripts
            readOnly: true
          - mountPath: /data
            name: data
      affinity: 
      volumes: 
        - name: config
          secret:
            optional: false
            secretName: rclone-config
        - configMap:
            defaultMode: 484
            name: rclone-script-cm
          name: scripts
        - configMap:
            name: nginx-conf-cm
          name: nginx-cfg
        - configMap:
            name: nginx-web-cm
          name: nginx-web
        - name: data
          persistentVolumeClaim:
            claimName: rclone-data
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-genuine-doc
  labels:
    app.kubernetes.io/name: genuine-doc
    app.kubernetes.io/instance: demo
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: docs-demo.genuine-dev.napbiotec.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-genuine-doc
                port: 
                  name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
stringData:
  rclone.conf: |
    [GoogleDriveNAp]
    type = drive
    scope = drive.readonly
    root_folder_id = <<Change-This>>
    token = <<Change-This>>
